/**
 * Do not edit directly
 * Generated on Fri, 26 Jan 2024 14:38:01 GMT
 */

export const lightTokens = {
	FEEDBACK_ERROR_STRONG_FILL_BG: "#c32945",
	FEEDBACK_ERROR_STRONG_FILL_FG: "#ffebee",
	FEEDBACK_ERROR_STRONG_FILL_EMP: "#ffffff",
	FEEDBACK_ERROR_MEDIUM_FILL_BG: "#ffd2db",
	FEEDBACK_ERROR_MEDIUM_FILL_FG: "#760f22",
	FEEDBACK_ERROR_MEDIUM_FILL_EMP: "#ea3b5a",
	FEEDBACK_ERROR_BG: "#ffffff",
	FEEDBACK_ERROR_FG: "#760f22",
	FEEDBACK_ERROR_EMP: "#ea3b5a",
	FEEDBACK_ERROR_BDR: {
		borderColor: "#ea3b5a",
		borderWidth: 2,
		borderStyle: "solid",
	},
	FEEDBACK_ERROR_BDR_FINE: {
		borderColor: "#ea3b5a",
		borderWidth: 1,
		borderStyle: "solid",
	},
	FEEDBACK_ERROR_TOAST: {
		borderColor: "#ea3b5a",
		borderWidth: 0,
		borderStyle: "solid",
	},
	FEEDBACK_WARNING_STRONG_FILL_BG: "#fcd900",
	FEEDBACK_WARNING_STRONG_FILL_FG: "#534803",
	FEEDBACK_WARNING_STRONG_FILL_EMP: "#534803",
	FEEDBACK_WARNING_MEDIUM_FILL_BG: "#fffdc8",
	FEEDBACK_WARNING_MEDIUM_FILL_FG: "#534803",
	FEEDBACK_WARNING_MEDIUM_FILL_EMP: "#a89103",
	FEEDBACK_WARNING_BG: "#ffffff",
	FEEDBACK_WARNING_FG: "#534803",
	FEEDBACK_WARNING_EMP: "#fcd900",
	FEEDBACK_WARNING_BDR: {
		borderColor: "#fcd900",
		borderWidth: 1,
		borderStyle: "solid",
	},
	FEEDBACK_WARNING_TOAST: {
		borderColor: "#fcd900",
		borderWidth: 0,
		borderStyle: "solid",
	},
	FEEDBACK_SUCCESS_STRONG_FILL_BG: "#32d17e",
	FEEDBACK_SUCCESS_STRONG_FILL_FG: "#074a27",
	FEEDBACK_SUCCESS_STRONG_FILL_EMP: "#074a27",
	FEEDBACK_SUCCESS_MEDIUM_FILL_BG: "#cefde4",
	FEEDBACK_SUCCESS_MEDIUM_FILL_FG: "#0e6c3b",
	FEEDBACK_SUCCESS_MEDIUM_FILL_EMP: "#32d17e",
	FEEDBACK_SUCCESS_BG: "#ffffff",
	FEEDBACK_SUCCESS_FG: "#0e6c3b",
	FEEDBACK_SUCCESS_EMP: "#32d17e",
	FEEDBACK_SUCCESS_BDR: {
		borderColor: "#32d17e",
		borderWidth: 1,
		borderStyle: "solid",
	},
	FEEDBACK_SUCCESS_TOAST: {
		borderColor: "#32d17e",
		borderWidth: 0,
		borderStyle: "solid",
	},
	FEEDBACK_INFO_STRONG_FILL_BG: "#3cc2f7",
	FEEDBACK_INFO_STRONG_FILL_FG: "#013d67",
	FEEDBACK_INFO_STRONG_FILL_EMP: "#013d67",
	FEEDBACK_INFO_MEDIUM_FILL_BG: "#e3f5fd",
	FEEDBACK_INFO_MEDIUM_FILL_FG: "#015b98",
	FEEDBACK_INFO_MEDIUM_FILL_EMP: "#00aff4",
	FEEDBACK_INFO_BG: "#ffffff",
	FEEDBACK_INFO_FG: "#015b98",
	FEEDBACK_INFO_EMP: "#00aff4",
	FEEDBACK_INFO_BDR: {
		borderColor: "#00aff4",
		borderWidth: 1,
		borderStyle: "solid",
	},
	FEEDBACK_INFO_TOAST: {
		borderColor: "#00aff4",
		borderWidth: 0,
		borderStyle: "solid",
	},
	FEEDBACK_FOCUS_INNER: {
		borderColor: "#ffffff",
		borderWidth: 1,
		borderStyle: "solid",
	},
	FEEDBACK_FOCUS_OUTER: {
		borderColor: "#ea3bae",
		borderWidth: 3,
		borderStyle: "solid",
	},
	ACTION_CTA_FILL_BG_DEFAULT: "#018cd9",
	ACTION_CTA_FILL_BG_HOVER: "#017aca",
	ACTION_CTA_FILL_BG_PRESSED: "#015b98",
	ACTION_CTA_FILL_FG: "#ffffff",
	ACTION_CTA_BG_DEFAULT: "#ffffff",
	ACTION_CTA_BG_HOVER: "#e3f5fd",
	ACTION_CTA_BG_PRESSED: "#ade5fb",
	ACTION_CTA_BG_SUBTLE: "#f2f3f4",
	ACTION_CTA_BG_TINT: "#e7ebef",
	ACTION_CTA_FG_DEFAULT: "#018cd9",
	ACTION_CTA_FG_HOVER: "#017aca",
	ACTION_CTA_FG_PRESSED: "#015b98",
	ACTION_CTA_BDR_DEFAULT: {
		borderColor: "#018cd9",
		borderWidth: 1,
		borderStyle: "solid",
	},
	ACTION_CTA_BDR_HOVER: {
		borderColor: "#017aca",
		borderWidth: 1,
		borderStyle: "solid",
	},
	ACTION_NEUTRAL_FILL_BG_DEFAULT: "#26496b",
	ACTION_NEUTRAL_FILL_BG_HOVER: "#163555",
	ACTION_NEUTRAL_FILL_BG_PRESSED: "#0a243f",
	ACTION_NEUTRAL_FILL_FG: "#ffffff",
	ACTION_NEUTRAL_BG_DEFAULT: "#ffffff",
	ACTION_NEUTRAL_BG_HOVER: "#e7ebef",
	ACTION_NEUTRAL_BG_PRESSED: "#d1dbe5",
	ACTION_NEUTRAL_FG: "#26496b",
	ACTION_NEUTRAL_BDR_DEFAULT: {
		borderColor: "#26496b",
		borderWidth: 1,
		borderStyle: "solid",
	},
	ACTION_NEUTRAL_BDR_HOVER: { borderColor: "#163555" },
	ACTION_ONDARK_FILL_BG_DEFAULT: "#ffffff",
	ACTION_ONDARK_FILL_BG_HOVER: "#f2f3f4",
	ACTION_ONDARK_FILL_BG_ACTIVE: "#95adc4",
	ACTION_ONDARK_FILL_BG_PRESSED: "#e7ebef",
	ACTION_ONDARK_FILL_FG: "#021529",
	ACTION_ONDARK_BG_DEFAULT: "#ffffff",
	ACTION_ONDARK_BG_HOVER: "#0a243f",
	ACTION_ONDARK_BG_ACTIVE: "#d1dbe5",
	ACTION_ONDARK_BG_PRESSED: "#021529",
	ACTION_ONDARK_FG_DEFAULT: "#ffffff",
	ACTION_ONDARK_FG_HOVER: "#3cc2f7",
	ACTION_ONDARK_FG_PRESSED: "#00aff4",
	ACTION_ONDARK_BDR_DEFAULT: {
		borderColor: "#ffffff",
		borderWidth: 1,
		borderStyle: "solid",
	},
	ACTION_ONDARK_BDR_HOVER: {
		borderColor: "#e7ebef",
		borderWidth: 1,
		borderStyle: "solid",
	},
	ACTION_DANGER_FILL_BG_DEFAULT: "#c32945",
	ACTION_DANGER_FILL_BG_HOVER: "#9d1b32",
	ACTION_DANGER_FILL_BG_PRESSED: "#760f22",
	ACTION_DANGER_FILL_FG: "#ffffff",
	ACTION_DANGER_BG_DEFAULT: "#ffffff",
	ACTION_DANGER_BG_HOVER: "#ffd2db",
	ACTION_DANGER_BG_PRESSED: "#ffb9c7",
	ACTION_DANGER_FG: "#c32945",
	ACTION_DANGER_BDR_DEFAULT: {
		borderColor: "#c32945",
		borderWidth: 1,
		borderStyle: "solid",
	},
	ACTION_DANGER_BDR_HOVER: {
		borderColor: "#9d1b32",
		borderWidth: 1,
		borderStyle: "solid",
	},
	ACTION_STANDARD_FILL_BG_DEFAULT: "#e7ebef",
	ACTION_STANDARD_FILL_BG_HOVER: "#bccbda",
	ACTION_STANDARD_FILL_BG_ACTIVE: "#018cd9",
	ACTION_STANDARD_FILL_FG_DEFAULT: "#163555",
	ACTION_STANDARD_FILL_FG_ACTIVE: "#ffffff",
	ACTION_STANDARD_FILL_EMP_DEFAULT: "#547698",
	ACTION_STANDARD_FILL_EMP_ACTIVE: "#ffffff",
	ACTION_STANDARD_FILL_EMP_ACCENT: "#018cd9",
	ACTION_STANDARD_BG_HOVER: "#e7ebef",
	ACTION_STANDARD_BG_DEFAULT: "#ffffff",
	ACTION_STANDARD_BG_ACTIVE: "#ade5fb",
	ACTION_STANDARD_FG: "#163555",
	ACTION_STANDARD_EMP: "#547698",
	ACTION_STANDARD_BDR_DEFAULT: {
		borderColor: "#bccbda",
		borderWidth: 1,
		borderStyle: "solid",
	},
	ACTION_STANDARD_BDR_ACTIVE: {
		borderColor: "#018cd9",
		borderWidth: 1,
		borderStyle: "solid",
	},
	ACTION_DISABLED_FILL_BG: "#d1dbe5",
	ACTION_DISABLED_FILL_FG: "#95adc4",
	ACTION_DISABLED_FG: "#95adc4",
	ACTION_DISABLED_BDR: {
		borderColor: "#95adc4",
		borderWidth: 1,
		borderStyle: "solid",
	},
	ACTION_DISABLED_BG: "#e7ebef",
	ACTION_DISABLED_CONTROL_BG_DEFAULT: "#d1dbe5",
	ACTION_DISABLED_CONTROL_BG_SUCCESS: "#82edb6",
	ACTION_DISABLED_CONTROL_BG_CTA: "#3cc2f7",
	ACTION_DISABLED_CONTROL_FG_DEFAULT: "#e7ebef",
	ACTION_DISABLED_CONTROL_FG_SUCCESS: "#cefde4",
	ACTION_DISABLED_CONTROL_FG_CTA: "#ade5fb",
	ACTION_NAV_BG_DEFAULT: "#ebf5ff",
	ACTION_NAV_BG_HOVER: "#97b3cf",
	ACTION_NAV_BG_ACTIVE: "#97b3cf",
	ACTION_NAV_FG_DEFAULT: "#264b70",
	ACTION_NAV_FG_HOVER: "#092541",
	ACTION_NAV_FG_ACTIVE: "#021529",
	ACTION_NAV_MAIN_FG_DEFAULT: "#7290ae",
	ACTION_NAV_MAIN_FG_HOVER: "#ffffff",
	ACTION_NAV_MAIN_BG_DEFAULT: "#000a13",
	ACTION_NAV_MAIN_BG_HOVER: "#0a243f",
	ACTION_NAV_MAIN_BG_ACTIVE: "#0a243f",
	ACTION_NAV_MAIN_ACCENT: "#00aff4",
	ACTION_ENABLED_CONTROL_BG_DEFAULT: "#bccbda",
	ACTION_ENABLED_CONTROL_BG_SUCCESS: "#32d17e",
	ACTION_ENABLED_CONTROL_BG_CTA: "#018cd9",
	ACTION_ENABLED_CONTROL_FG: "#ffffff",
	LAYOUT_SURFACE_LEVEL1: "#ffffff",
	LAYOUT_SURFACE_LEVEL1_RGB: "255, 255, 255",
	LAYOUT_SURFACE_LEVEL2: "#f2f3f4",
	LAYOUT_SURFACE_LEVEL3: "#e7ebef",
	LAYOUT_SURFACE_LEVEL4: "#d1dbe5",
	LAYOUT_SURFACE_LEVEL5: "#bccbda",
	LAYOUT_CONTENT_PRIMARY: "#163555",
	LAYOUT_CONTENT_SECONDARY: "#26496b",
	LAYOUT_CONTENT_TERTIARY: "#3b5e82",
	LAYOUT_CONTENT_BDR_LIGHT: {
		borderColor: "#ffffff",
		borderWidth: 2,
		borderStyle: "solid",
	},
	LAYOUT_CONTENT_BDR_LIGHT_FINE: {
		borderColor: "#ffffff",
		borderWidth: 1,
		borderStyle: "solid",
	},
	LAYOUT_CONTENT_BDR_MEDIUM: {
		borderColor: "#e7ebef",
		borderWidth: 2,
		borderStyle: "solid",
	},
	LAYOUT_CONTENT_SUBTLE: "#7290ae",
	LAYOUT_NAV_BG: "#ebf5ff",
	LAYOUT_NAV_FG: "#3b6288",
	LAYOUT_NAV_HIGHLIGHT: "#00aff4",
	LAYOUT_NAV_SUBTLE: "#97b3cf",
	LAYOUT_COMPONENT_BG_DEFAULT: "#ffffff",
	LAYOUT_COMPONENT_BG_SUBTLE: "#f2f3f4",
	LAYOUT_COMPONENT_BG_TINT: "#e7ebef",
	LAYOUT_COMPONENT_BG_ODD: "#ffffff",
	LAYOUT_COMPONENT_BG_EVEN: "#f2f3f4",
	LAYOUT_COMPONENT_FG_DEFAULT: "#163555",
	LAYOUT_COMPONENT_FG_SUBTLE: "#7290ae",
	LAYOUT_COMPONENT_FG_SECONDARY: "#26496b",
	LAYOUT_COMPONENT_FG_TERTIARY: "#3b5e82",
	LAYOUT_COMPONENT_HEADER_FG: "#163555",
	LAYOUT_COMPONENT_HEADER_BG: "#ffffff",
	LAYOUT_COMPONENT_BDR_SUBTLE: {
		borderColor: "#e7ebef",
		borderWidth: 1,
		borderStyle: "solid",
	},
	LAYOUT_COMPONENT_BDR_TINT: {
		borderColor: "#e7ebef",
		borderWidth: 1,
		borderStyle: "solid",
	},
	LAYOUT_COMPONENT_BDR_DASHED: {
		borderColor: "#bccbda",
		borderWidth: 2,
		borderStyle: "dashed",
	},
	LAYOUT_COMPONENT_BDR_DEFAULT: {
		borderColor: "#bccbda",
		borderWidth: 1,
		borderStyle: "solid",
	},
	LAYOUT_COMPONENT_BDR_HOVER: {
		borderColor: "#7290ae",
		borderWidth: 1,
		borderStyle: "solid",
	},
	LAYOUT_COMPONENT_BDR_ACTIVE: {
		borderColor: "#018cd9",
		borderWidth: 1,
		borderStyle: "solid",
	},
	LAYOUT_COMPONENT_BDR_ERROR: {
		borderColor: "#ea3b5a",
		borderWidth: 1,
		borderStyle: "solid",
	},
	LAYOUT_PROGRESS_BLUE: {
		borderColor: "#00aff4",
		borderWidth: 6,
		borderStyle: "solid",
	},
	LAYOUT_PROGRESS_GREEN: {
		borderColor: "#32d17e",
		borderWidth: "6",
		borderStyle: "solid",
	},
	LAYOUT_PROGRESS_CHANNEL: {
		borderColor: "#e7ebef",
		borderWidth: 6,
		borderStyle: "solid",
	},
	LAYOUT_PROGRESS_CHANNEL_INVERSE: {
		borderColor: "#021529",
		borderWidth: 6,
		borderStyle: "solid",
	},
	LAYOUT_PROGRESS_INDICATOR: {
		borderColor: "#7290ae",
		borderWidth: 6,
		borderStyle: "solid",
	},
	LAYOUT_PROGRESS_INVERSE: {
		borderColor: "#ffffff",
		borderWidth: 6,
		borderStyle: "solid",
	},
	LAYOUT_INVERSE_PRIMARY: "#f2f3f4",
	LAYOUT_INVERSE_SECONDARY: "#e7ebef",
	LAYOUT_INVERSE_BG: "#021529",
};
